# Use an official Python image
FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt


# Copy project files
COPY . .

# Expose port (optional, for documentation)
EXPOSE 8000

# Run the Daphne ASGI server
CMD ["daphne", "-b", "0.0.0.0", "-p", "8000", "socialmedia.asgi:application"]